config/routes.rb
Riskmanager::Application.routes.draw do
  
    scope ENV['RAILS_RELATIVE_URL_ROOT'] do 
      resources :projects do
        get 'export',      :on => :member
        get 'tags',        :on => :member
        get 'graph',       :on => :member
        get 'risk_levels', :on => :member

        resources :risk_assets

        resources :risks do
          get 'checklists',      :on => :collection
          get 'assets',          :on => :member
          post 'assign_asset',   :on => :member
          post 'unassign_asset', :on => :member
          resources :comments
          resources :checklists do
            resources :checklist_items
          end
          resources :attachments
        end
      end

      resources :risk_configurations do
      	resources :impacts
      	resources :risk_consequences
      	resources :risk_probabilities
      	resources :risk_levels
        resources :risk_asset_values
      end

      resources :attachments

      resources :users

      resource :changes
      resource :not_approved
      resource :additional_infos
      resource :session

      get  "oauth/new"  => "oauth#new"
      get  "oauth/code" => "oauth#code"

      get  "login"                  => "login#index"
      get  "login/failed"           => "login#failed"
      get  "login/connect"          => "login#connect"
      post "login/connectaccounts"  => "login#connectaccounts"
      get  "login/switch"           => "login#switch"

      get '/auth/:provider/callback' => 'sessions#create'
      match '/auth/failure' => 'sessions#failure'

      root :to => "home#index"
    end

  match "*path" => "home#fix"
  root :to => redirect("/risk/")

end

app/models/risk_configuration.rb
class RiskConfiguration < ActiveRecord::Base
	has_many :risk_levels
	has_many :risk_probabilities
	has_many :risk_consequences
	has_many :impacts
    has_many :risk_asset_values
	has_paper_trail

	def visible_impacts
		impacts.where("hidden IS NULL OR hidden = ?", false)
	end
	def hidden_impacts
		impacts.where("hidden = ?", true)
	end

    def find_level(probability, consequence)
        sum = probability.weight * consequence.weight
        level = risk_levels.select{ |l| l.weight >= sum }.sort_by{|l| l.weight }.first
        level || risk_levels.sort_by{|l| l.weight }.last
    end

end

app/controllers/risk_configurations_controller.rb
class RiskConfigurationsController < ApplicationController
  before_filter :ensure_signed_in
  before_filter :ensure_approved
  before_filter :ensure_admin  
  
  # GET /risk_configurations
  # GET /risk_configurations.json
  def index
    @risk_configurations = RiskConfiguration.all

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @risk_configurations }
    end
  end

  # GET /risk_configurations/1
  # GET /risk_configurations/1.json
  def show
    @risk_configuration = RiskConfiguration.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @risk_configuration }
    end
  end

  # GET /risk_configurations/new
  # GET /risk_configurations/new.json
  def new
    @risk_configuration = RiskConfiguration.new

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @risk_configuration }
    end
  end

  # GET /risk_configurations/1/edit
  def edit
    @risk_configuration = RiskConfiguration.find(params[:id])
  end

  # POST /risk_configurations
  # POST /risk_configurations.json
  def create
    @risk_configuration = RiskConfiguration.new(params[:risk_configuration])

    respond_to do |format|
      if @risk_configuration.save

        @risk_configuration.risk_levels.create [
          {:name => "High", :weight => 5000}, {:name => "Medium", :weight => 2500}, {:name => "Low", :weight => 500} 
        ]
        @risk_configuration.risk_probabilities.create [
          {:name => "High", :weight => 100}, {:name => "Medium", :weight => 50}, {:name => "Low", :weight => 10} 
        ]
        @risk_configuration.risk_consequences.create [
          {:name => "High", :weight => 100}, {:name => "Medium", :weight => 50}, {:name => "Low", :weight => 10} 
        ]
        @risk_configuration.risk_asset_values.create [
          {:name => "High", :weight => 100}, {:name => "Medium", :weight => 50}, {:name => "Low", :weight => 10} 
        ]
        low_risk = @risk_configuration.risk_levels.where({:weight => 500}).first
		    @risk_configuration.impacts.create [
          {:name => "Confidentiality", :risk_level => low_risk}, 
          {:name => "Integrity", :risk_level => low_risk}, 
          {:name => "Availability", :risk_level => low_risk} 
        ]
        format.html { redirect_to(@risk_configuration, :notice => 'Risk configuration was successfully created.') }
        format.json  { render :json => @risk_configuration, :status => :created, :location => @risk_configuration }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @risk_configuration.errors, :status => :unprocessable_entity }
      end
    end
  end

  def create_defaults(itemspec, config) 
	default_values = [["High", 100], ["Medium", 50], ["Low", 10]]
	default_values.each do |name, weight|
		item = itemspec.new
		item.name = name
		item.weight = weight
		item.risk_configuration = config
		item.save
	end
  end
  
  # PUT /risk_configurations/1
  # PUT /risk_configurations/1.json
  def update
    @risk_configuration = RiskConfiguration.find(params[:id])

    respond_to do |format|
      if @risk_configuration.update_attributes(params[:risk_configuration])
        format.html { redirect_to(@risk_configuration, :notice => 'Risk configuration was successfully updated.') }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @risk_configuration.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /risk_configurations/1
  # DELETE /risk_configurations/1.json
  def destroy
    @risk_configuration = RiskConfiguration.find(params[:id])
    @risk_configuration.destroy

    respond_to do |format|
      format.html { redirect_to(risk_configurations_url) }
      format.json  { head :ok }
    end
  end
end

app/helpers/risk_configurations_helper.rb
module RiskConfigurationsHelper


end

app/views/risk_configurations/_form.html.erb
<%= form_for(@risk_configuration) do |f| %>
  <% if @risk_configuration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@risk_configuration.errors.count, "error") %> prohibited this risk_configuration from being saved:</h2>

      <ul>
      <% @risk_configuration.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>


  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/risk_configurations/edit.html.erb
<h1>Editing risk_configuration</h1>

<%= render 'form' %>

<%= link_to 'Show', @risk_configuration %> |
<%= link_to 'Back', risk_configurations_path %>

app/views/risk_configurations/index.html.erb
<% content_for :title, " - Configurations" %>

<h1>Risk Configurations</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
  </tr>

<% @risk_configurations.each do |risk_configuration| %>
  <tr>
    <td><%= link_to risk_configuration.name, risk_configuration %></td>
    <td><%= button_to 'Rename', edit_risk_configuration_path(risk_configuration), :method => :get, :class => "btn btn-small" %></td>
    <td><%= button_to 'Delete', risk_configuration, :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-small" %></td>
  </tr>
<% end %>
</table>


<a href="<%= new_risk_configuration_path %>" class="btn"><i class="icon-plus"></i> New Risk configuration</a>

app/views/risk_configurations/new.html.erb
<h1>New risk_configuration</h1>

<%= render 'form' %>

<%= link_to 'Back', risk_configurations_path %>

app/views/risk_configurations/show.html.erb
<p id="notice"><%= notice %></p>

<h1><b>Configuration:</b> <%= @risk_configuration.name %></h1>

<div class="span5">
<h2>Consequences</h2>
<table class="table">
<% @risk_configuration.risk_consequences.sort_by{|p| p.weight}.reverse().each do |risk_consequence| %>
  <tr>
    <th><%= risk_consequence.name %></th>
    <td><%= risk_consequence.weight %></td>
    <td><%= button_to 'Edit', edit_risk_configuration_risk_consequence_path(@risk_configuration, risk_consequence), :method => :get, :class => "btn btn-small" %></td>
    <td><%= button_to 'Delete', risk_configuration_risk_consequence_path(@risk_configuration, risk_consequence), :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-small" %></td>
  </tr>
<% end %>
  <tr>
	<td colspan=4>
        <a href="<%= new_risk_configuration_risk_consequence_path(@risk_configuration) %>" 
    class="btn btn-small"><i class="icon-plus"></i> Add</a>
	</td>
  </tr>	
</table>
</div>

<div class="span5">
<h2>Probabilities</h2>
<table class="table">
<% @risk_configuration.risk_probabilities.sort_by{|p| p.weight}.reverse().each do |risk_probability| %>
  <tr>
    <th><%= risk_probability.name %></th>
    <td><%= risk_probability.weight %></td>
    <td><%= button_to 'Edit', edit_risk_configuration_risk_probability_path(@risk_configuration, risk_probability), :method => :get, :class => "btn btn-small" %></td>
    <td><%= button_to 'Delete', risk_configuration_risk_probability_path(@risk_configuration, risk_probability), :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-small" %></td>
  </tr>
<% end %>
  <tr>
	<td colspan=4>
		<a href="<%= new_risk_configuration_risk_probability_path(@risk_configuration) %>" 
    class="btn btn-small"><i class="icon-plus"></i> Add</a>
	</td>
  </tr>
</table>
</div>


<div class="span5">
<h2>Risk levels</h2>
<table class="table">

<% @risk_configuration.risk_levels.sort_by{|p| p.weight}.reverse().each do |risk_level| %>
  <tr>
    <th><%= risk_level.name %></th>
    <td><%= risk_level.weight %></td>
    <td><%= button_to 'Edit', edit_risk_configuration_risk_level_path(@risk_configuration, risk_level), :method => :get, :class => "btn btn-small" %></td>
    <td><%= button_to 'Delete', risk_configuration_risk_level_path(@risk_configuration, risk_level), :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-small" %></td>
  </tr>
<% end %>
  <tr>
	<td colspan=4>
    <a href="<%= new_risk_configuration_risk_level_path(@risk_configuration) %>" 
    class="btn btn-small"><i class="icon-plus"></i> Add</a>
	</td>
  </tr>
</table>
</div>

<div class="span5">
<h2>Calculated risk levels</h2>
<table class="table">
  <tr>
    <th> </th>
    <% @risk_configuration.risk_consequences.sort_by{|p| p.weight}.each do |rc| %>
      <th><%= rc.name %></th>
    <% end %>
  </tr>
<% @risk_configuration.risk_probabilities.sort_by{|p| p.weight}.each do |rp| %>
  <tr>
    <th><%= rp.name %></th>
    <% @risk_configuration.risk_consequences.sort_by{|p| p.weight}.each do |rc| %>
      <% rl = @risk_configuration.find_level(rp, rc) %>
      <td title="<%= rp.weight * rc.weight %>" class="risk_level_<%= rl.color %>"><%= rl.name %></td>
    <% end %>
  </tr>
<% end %>
</table>
</div>



<div class="span5">
<h2>Impacts</h2>
<table class="table">

<% @risk_configuration.impacts.sort_by{|c| [c.hidden ? 1 : 0, c.name]}.each do |impact| %>
  <tr class="<%= impact.hidden ? "muted" : "" %>">
    <th><%= impact.name %></th>
    <td><%= impact.risk_level.name %></td>
    <td><%= button_to 'Edit', edit_risk_configuration_impact_path(@risk_configuration, impact), :method => :get, :class => "btn btn-small" %></td>
    <td><%= button_to 'Delete', risk_configuration_impact_path(@risk_configuration, impact), :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-small" %></td>
  </tr>
<% end %>
  <tr>
	<td colspan=4>
    <a href="<%= new_risk_configuration_impact_path(@risk_configuration) %>" 
    class="btn btn-small"><i class="icon-plus"></i> Add</a>
	</td>
  </tr>
</table>
</div>

<div class="span5">
<h2>Asset values</h2>
<table class="table">

<% @risk_configuration.risk_asset_values.sort_by{|c| c.weight}.reverse().each do |asset_value| %>
  <tr>
    <th><%= asset_value.name %></th>
    <td><%= asset_value.weight %></td>
    <td><%= button_to 'Edit', edit_risk_configuration_risk_asset_value_path(@risk_configuration, asset_value), :method => :get, :class => "btn btn-small" %></td>
    <td><%= button_to 'Delete', risk_configuration_risk_asset_value_path(@risk_configuration, asset_value), :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-small" %></td>
  </tr>
<% end %>
  <tr>
  <td colspan=4>
    <a href="<%= new_risk_configuration_risk_asset_value_path(@risk_configuration) %>" 
    class="btn btn-small"><i class="icon-plus"></i> Add</a>
  </td>
  </tr>
</table>
</div>