config/routes.rb
Riskmanager::Application.routes.draw do
  
    scope ENV['RAILS_RELATIVE_URL_ROOT'] do 
      resources :projects do
        get 'export',      :on => :member
        get 'tags',        :on => :member
        get 'graph',       :on => :member
        get 'risk_levels', :on => :member

        resources :risk_assets

        resources :risks do
          get 'checklists',      :on => :collection
          get 'assets',          :on => :member
          post 'assign_asset',   :on => :member
          post 'unassign_asset', :on => :member
          resources :comments
          resources :checklists do
            resources :checklist_items
          end
          resources :attachments
        end
      end

      resources :risk_configurations do
      	resources :impacts
      	resources :risk_consequences
      	resources :risk_probabilities
      	resources :risk_levels
        resources :risk_asset_values
      end

      resources :attachments

      resources :users

      resource :changes
      resource :not_approved
      resource :additional_infos
      resource :session

      get  "oauth/new"  => "oauth#new"
      get  "oauth/code" => "oauth#code"

      get  "login"                  => "login#index"
      get  "login/failed"           => "login#failed"
      get  "login/connect"          => "login#connect"
      post "login/connectaccounts"  => "login#connectaccounts"
      get  "login/switch"           => "login#switch"

      get '/auth/:provider/callback' => 'sessions#create'
      match '/auth/failure' => 'sessions#failure'

      root :to => "home#index"
    end

  match "*path" => "home#fix"
  root :to => redirect("/risk/")

end

app/models/risk_asset.rb
class RiskAsset < ActiveRecord::Base
  belongs_to :risk_asset_value
  belongs_to :project
  has_and_belongs_to_many :risks
  attr_accessible :description, :name, :risk_asset_value_id, :owner
  has_paper_trail

  def self.to_change_string(version)
    if (version.event == "create") then
      c = RiskAsset.find(version.item_id)
      s = "New risk asset for project #{c.project.id}: <ul>" + 
        "<li>Name: <em>" + ERB::Util.html_escape(c.name) + "</em></li>" + 
      	"<li>Value: <em>" + ERB::Util.html_escape(c.risk_asset_value.name) + "</em></li>" +
      	"<li>Description: <em>" + ERB::Util.html_escape(c.description) + "</em></li>" +
      	"</ul>"
      s.html_safe
    else
      version.changeset_as_html
    end
  end

end

app/controllers/risk_assets_controller.rb
class RiskAssetsController < ApplicationController
  before_filter :ensure_signed_in
  before_filter :ensure_approved  

  def index
    if (params[:term]) then
      @assets = current_project.risk_assets.where("name LIKE :term", {:term => params[:term] + "%"})
    else
      @assets = current_project.risk_assets
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @assets }
    end
  end

  def show
    @asset = RiskAsset.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @asset }
    end
  end


  def new
    @asset = RiskAsset.new

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @asset }
    end
  end

  def edit
    @asset = RiskAsset.find(params[:id])
  end

  def create
    @asset = RiskAsset.new(params[:risk_asset])
    @asset.project = current_project
    respond_to do |format|
      if @asset.save
        format.html { redirect_to(project_risk_assets_path(current_project), :notice => 'Asset was successfully created.') }
        format.json  { render :json => @asset, :status => :created}
      else
        format.html { render :action => "new" }
        format.json  { render :json => @asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @asset = RiskAsset.find(params[:id])

    respond_to do |format|
      if @asset.update_attributes(params[:risk_asset])
        format.html { redirect_to(project_risk_assets_path(current_project), :notice => 'Asset was successfully updated.') }
        format.json  { render :json => @asset }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @asset = RiskAsset.find(params[:id])
    @asset.destroy

    respond_to do |format|
      format.html { redirect_to(project_risk_assets_path(current_project)) }
      format.json  { head :ok }
    end
  end






end

app/views/risk_assets/_form.html.erb
<%= form_for([current_project, @asset]) do |f| %>
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :rows => 5 %>
  </div>  
  <div class="field">
    <%= f.label :owner %>
    <%= f.text_field :owner %>
  </div>  

  <div class="field">
    <%= f.label :risk_asset_value %>
  <%= select(:asset, :risk_asset_value_id, current_project.risk_configuration.risk_asset_values.sort_by{|l| l.weight }.reverse().collect{|l| [l.name + " - " + (l.description || ""), l.id] } ) %>
  </div>

  <div class="actions">
    <%= f.submit :class =>"btn btn-primary" %>
  </div>
<% end %>

app/views/risk_assets/edit.html.erb
<h1>Editing asset</h1>

<%= render 'form' %>

<%= link_to 'Back', project_risk_assets_path(current_project) %>

app/views/risk_assets/index.html.erb
<% content_for :title, " - Assets" %>


<% content_for :sidebar do %>
  <li class="nav-header">Value Definitions</li>
    <table class="table">
      <% current_project.risk_configuration.risk_asset_values.sort_by{|v| v.weight}.reverse.each do |v| %>
        <tr>
          <th><%= v.name %></th>
          <td><%= v.description %></td>
        </tr>
      <% end %>
    </table>
<% end %>


<% @breadcrumbs.push(["Assets", ""]) %>
<%= render 'layouts/breadcrumb' %>

<div style="float: right; text-align: right">

  <a href="<%= new_project_risk_asset_path(current_project) %>" class="btn"><i class="icon-plus"></i> New asset</a>
</div>

<h1>Assets</h1>

<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th>Owner</th>
      <th>Description</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @assets.sort_by{|a| [ -a.risk_asset_value.weight, a.name ] }.each do |asset| %>
      <tr>
        <td data-sort-key="<%= asset.name %>"><%= link_to asset.name, [current_project, asset] %></td>
        <td data-sort-key="<%= asset.risk_asset_value.weight %>"><abbr title="<%= asset.risk_asset_value.description %>"><%= asset.risk_asset_value.name %></abbr></td>
        <td><%= asset.owner %></td>
        <td><%= asset.description %></td>
        <td><%= button_to 'Edit', edit_project_risk_asset_path(current_project, asset), :method => :get, :class => "btn btn-small" %></td>
        <td><%= button_to 'Delete', [current_project, asset], :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-small" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/risk_assets/new.html.erb
<h1>New asset</h1>

<%= render 'form' %>

<%= link_to 'Back', project_risk_assets_path(current_project) %>

app/views/risk_assets/show.html.erb
<%= content_for :title, " - " << @asset.project.name << " \\ " << @asset.name %>

<p id="notice"><%= notice %></p>



<% @breadcrumbs.push(["Assets", project_risk_assets_path(current_project)]) %>
<% @breadcrumbs.push([@asset.name, ""]) %>
<%= render 'layouts/breadcrumb' %>


<h1><%= @asset.name %></h1>

<h5>Value</h5> 
<%= @asset.risk_asset_value.name %> - <%= @asset.risk_asset_value.description %>

<h5>Owner</h5> 
<%= @asset.owner %>


<div id="description">
<h5>Description</h5> 
  <%= @asset.description %>
</div>



<h3>Risks associated with this asset:</h3>
<table class="risks table table-striped table-condensed">
  <thead>
    <tr>
      <th>Impact</th>
      <th>Id</th>
      <th>Title</th>
      <th>Consequence</th>
      <th>Probability</th>
      <th>Risk level</th>
    </tr>
  </thead>
  <tbody>
<% @asset.risks.sort_by{|r| [r.impact.name, r.title]}.each do |risk| %>
  <tr>
    <td><%= risk.impact.name %></td>
    <td data-sort-key="<%= risk.id %>"><%= risk.risk_id %></td>
    <td><%= link_to risk.title, project_risk_path(current_project, risk) %></td>
    <td data-sort-key="<%= risk.risk_consequence.weight %>"><%= risk.risk_consequence.name %></td>
    <td data-sort-key="<%= risk.risk_probability.weight %>"><%= risk.risk_probability.name %></td>
    <td data-sort-key="<%= risk.risk_level.weight %>" class="<%= risk.accepted ? "" : "tooHigh" %>"><%= risk.risk_level.name %></td>
    
  </tr>
<% end %>
</tbody>
</table>