config/routes.rb
Riskmanager::Application.routes.draw do
  
    scope ENV['RAILS_RELATIVE_URL_ROOT'] do 
      resources :projects do
        get 'export',      :on => :member
        get 'tags',        :on => :member
        get 'graph',       :on => :member
        get 'risk_levels', :on => :member

        resources :risk_assets

        resources :risks do
          get 'checklists',      :on => :collection
          get 'assets',          :on => :member
          post 'assign_asset',   :on => :member
          post 'unassign_asset', :on => :member
          resources :comments
          resources :checklists do
            resources :checklist_items
          end
          resources :attachments
        end
      end

      resources :risk_configurations do
      	resources :impacts
      	resources :risk_consequences
      	resources :risk_probabilities
      	resources :risk_levels
        resources :risk_asset_values
      end

      resources :attachments

      resources :users

      resource :changes
      resource :not_approved
      resource :additional_infos
      resource :session

      get  "oauth/new"  => "oauth#new"
      get  "oauth/code" => "oauth#code"

      get  "login"                  => "login#index"
      get  "login/failed"           => "login#failed"
      get  "login/connect"          => "login#connect"
      post "login/connectaccounts"  => "login#connectaccounts"
      get  "login/switch"           => "login#switch"

      get '/auth/:provider/callback' => 'sessions#create'
      match '/auth/failure' => 'sessions#failure'

      root :to => "home#index"
    end

  match "*path" => "home#fix"
  root :to => redirect("/risk/")

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :risk_configuration
  has_many :risks
  has_many :risk_assets
  has_paper_trail
  
  def days_since_creation
    (Date.today - created_at.to_date).to_i + 1
  end
  
  def risks_at(date)
    risks.collect{|r| r.version_at(date)}
  end

  def visible_impacts
    impacts = Set.new risk_configuration.visible_impacts.to_a
    impacts.merge(risks.collect{|r| r.impact}.to_a)
    impacts.sort_by{|i| [i.hidden ? 1 : 0, i.name]}
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :ensure_signed_in
  before_filter :ensure_approved  
  include ProjectsHelper

  
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @project }
    end
  end

  def graph
    @project = Project.find(params[:id])
    rv = risk_versions
    respond_to do |format|
      format.json  { render :json => { 
          :week_ticks => week_ticks(rv), 
          :month_ticks => month_ticks(rv), 
          :total_risk => total_risk(rv), 
          :accepted_risk => accepted_risk(rv) 
        } }
    end    
  end

  def risk_levels
    @project = Project.find(params[:id])
    @risk_configuration = @project.risk_configuration
    respond_to do |format|
      format.html # risk_levels.html.erb
    end
  end



  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, :notice => 'Project was successfully created.') }
        format.json  { render :json => @project, :status => :created, :location => @project }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to(@project, :notice => 'Project was successfully updated.') }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to(projects_url) }
      format.json  { head :ok }
    end
  end

  def tags
    @term = params[:term].downcase
    @tags = Project.find(params[:id]).risks.tag_counts.map{ |t| t.name }.select{ |t| t.downcase.start_with? @term }
    render :json => @tags
  end

  def export
    @project = Project.find(params[:id])    
    @include_comments = params[:include_comments]
    @tag = params[:tag]    
    if (@tag) then
      @risks = @project.risks.tagged_with(params[:tag])
    else 
      @risks = @project.risks
    end
    @date = Date.parse(params[:at]) rescue NIL
    if (@date) then
      @risks = @risks.collect{|r| r.version_at(@date)}.reject{|r| r == nil}
    end
    respond_to do |format|
      format.html { render :layout => 'export_layout' }
    end
  end


end

app/helpers/projects_helper.rb
module ProjectsHelper

    def total_risk(versions)
		versions.each_with_index.map{|r, i| [ i, r.total ] }
	end
    
    def accepted_risk(versions)
		versions.each_with_index.map{|r, i| [ i, r.accepted ]}
	end

	def month_ticks(versions)
		days = @project.days_since_creation 
		versions.each_with_index.map{|r, i|
			d = (Date.today - (days - i))
			if (d == (d.beginning_of_month + 15)) then
				{ :v => i, :label => d.strftime("%b") }
			else
				{}
			end
		}.reject{|d| d == {}}
	end
	def week_ticks(versions)
		days = @project.days_since_creation 
		versions.each_with_index.map{|r, i|
			d = (Date.today - (days - i))
			if (d == d.beginning_of_week) then
				{ :v => i, :label => d.strftime("%d.%m") }
			else
				{}
			end
		}.reject{|d| d == {}}
	end
	
	def risk_versions
		days = @project.days_since_creation 
		risk = risk_at_dates(days)
		current_risks = @project.risks.map{|r| { :accepted => r.accepted }}
		risk.push RiskAtDay.new({ 
			:date => Date.today, 
			:total => current_risks.count(), 
			:accepted => current_risks.map{|a| a[:accepted] }.count{|a| a } 
			})
		risk
	end

	def risk_at_dates(days)
		risk_at_date = RiskAtDay.where({:project_id => @project.id})
		days.times do |i| 
			date = Date.today - (days - i) + 1 
			if (!risk_at_date.any? { |r| r.date == date })
				ra = @project.risks_at(Date.today - (days - i) + 1).select{|rr| rr != NIL}.map{|r| { :accepted => r.accepted }}
				risks = RiskAtDay.new({ 
					:date => date, 
					:total => ra.count(), 
					:accepted => ra.map{|a| a[:accepted] }.count{|a| a },
					:project_id => @project.id
				})		
				risks.save
				risk_at_date.push risks
			end
		end
		risk_at_date
	end

end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :risk_configuration %>
    <%= select("project", "risk_configuration_id", RiskConfiguration.all.sort_by{|c| c.name }.collect{|c| [c.name, c.id] } ) %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/export.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
<%= File.read "#{Rails.root}/public/stylesheets/export.css" %>
</style>
<title><%= @project.name %></title>
</head>
<body>
	<header class="date">Eksportert: <%= Date.today %> - <%= current_user.full_name %> <% if (@tag) then %> - tag: <%= @tag %> <% end %>
		<% if (@date) %> - Dato: <%= @date %> <% end %>
	</header>
	<h1><%= @project.name %></h1>
	<table class="risk_list">
		<tr>
			<th class="impact"></th>
			<% @project.risk_configuration.risk_levels.sort_by(&:weight).each do |risk_level| %>
				<th class="impact"><%= risk_level.name %></th>
			<% end %>
		</tr>
	<% @project.visible_impacts.each do |impact| %>
		<tr>
			<th><%= impact.name %></th>
			<% @project.risk_configuration.risk_levels.sort_by(&:weight).each do |risk_level| %>
				<% 
				 count =  @risks.select{|r| r.impact == impact && r.risk_level == risk_level}.count()
				 count_overridden = @risks.select{|r| r.impact == impact && r.risk_level == risk_level && r.accepted_override }.count() 
				%>
				<td class="<%= (count - count_overridden) > 0 && risk_level.weight > impact.risk_level.weight ? "tooHigh" : "" %>">
					<%= count - count_overridden %>
					<% if (count_overridden > 0)  %>
						+ <span><%= count_overridden %></span>
					<% end %>
				</td>
			<% end %>
		</tr>
	<% end %>
	</table>

	<% @risks.each do |r| %>
	 <div class="riskContainer">
      	<h3><%= r.title %></h3>
	  	<div class="risk">
			<table>
				<thead>
					<tr>
						<td><label>ID:</label> <%= r.risk_id %></td>
						<td><label>Probability:</label> <%= r.risk_probability.name %></td>
						<td><label>Consequence:</label> <%= r.risk_consequence.name %></td>
						<td><label>Level:</label> <%= r.risk_level.name %></td>
						<td><label>Impact:</label> <%= r.impact.name %></td>
					</tr>
				</thead>
			</table>
			<div class="description">
				<label>Description:</label>
				<%= r.description_html.html_safe %>
			</div>
			<div class="description">
				<label>Mitigation:</label>
				<%= r.mitigation_html.html_safe %>

			</div>
			<% if (@include_comments) %>
				<%  r.root_comments.sort_by{ |f1| f1[:created_at] }.reverse.each do |c| %>
					<div class="comment">
						<label><%=c.user.full_name %> - <%= c.created_at.strftime("%d.%m %H:%M") %> :</label>
						<%= c.body_html.html_safe %>
					</div>
				<% end %>
			<% end %>
	  	</div>
	 </div>
	<% end %>
</body>
</html>

app/views/projects/index.html.erb
<% content_for :title, " - Projects" %>

<h1>Projects</h1>

<table class="table">
  <% if current_user.is_admin? then %>
    <tr>
      <th>Name</th>
        <th>Risk configuration</th>
    <% if current_user.is_admin? then %>
        <th></th>
        <th></th>
    <% end %>
    </tr>
  <% end %>

<% @projects.each do |project| %>
  <tr>
    <td><%= link_to project.name, project %></td>
    <% if current_user.is_admin? then %>
      <td><%= project.risk_configuration.name %></td>
      <td><%= button_to 'Edit', edit_project_path(project), :method => :get, :class => "btn btn-small" %></td>

      <td><%= button_to 'Destroy', project, :confirm => 'Are you sure?', :method => :delete, :class => "btn btn-small" %></td>
    <% end %>
  </tr>
<% end %>
</table>


<% if current_user.is_admin? then %>
  <a href="<%= new_project_path %>" class="btn"><i class="icon-plus"></i> New Project</a>
<% end %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/risk_levels.html.erb
<% content_for :title, " - " << @project.name %>

<% @breadcrumbs.push([@project.name, project_path(@project)]) %>
<% @breadcrumbs.push(["Risk levels", ""]) %>
<%= render 'layouts/breadcrumb' %>

<h1>Risk levels</h1>

<div class="span6">
<table class="table risk_levels">
  <tr>
    <th> </th>
    <th> </th>
    <th colspan="<%= @risk_configuration.risk_consequences.count %>"><label>Consequences</label></th>
  </tr>
  <tr>
    <th rowspan="<%= @risk_configuration.risk_probabilities.count + 1 %>" class="vertical_label"><br><br><label>Probabilities</label></th>
    <th> </th>
    <% @risk_configuration.risk_consequences.sort_by{|p| p.weight}.each do |rc| %>
      <th><%= rc.name %></th>
    <% end %>
  </tr>
<% @risk_configuration.risk_probabilities.sort_by{|p| p.weight}.each do |rp| %>
  <tr>
    <th><%= rp.name %></th>
    <% @risk_configuration.risk_consequences.sort_by{|p| p.weight}.each do |rc| %>
      <% rl = @risk_configuration.find_level(rp, rc) %>
      <td class="risk_level_<%= rl.color %>"><%= rl.name %></td>
    <% end %>
  </tr>
<% end %>
</table>
</div>

app/views/projects/show.html.erb
<% content_for :title, " - " << @project.name %>

<% content_for :sidebar do %>
    <li class="nav-header">Content</li>
    <li><%= link_to "List risks", project_risks_path(@project) %></li>
    <li><%= link_to "List assets", project_risk_assets_path(@project) %></li>
    <li><%= link_to "Show checklists", checklists_project_risks_path(@project) %></li>
    <li><%= link_to "Risk levels", risk_levels_project_path(@project) %></li>
    <% if current_user.is_admin? then %>
        <li class="nav-header">Project</li>
        <li><%= link_to 'Edit project', edit_project_path(@project) %></li>
        <li><%= link_to 'Export project', export_project_path(@project) %></li>
    <% end %>
<% end%>

<script type="text/javascript" src="<%= ENV['RAILS_RELATIVE_URL_ROOT'] %>/assets/mochikit/MochiKit.js"></script>
<script type="text/javascript" src="<%= ENV['RAILS_RELATIVE_URL_ROOT'] %>/assets/plotkit/Base.js"></script>
<script type="text/javascript" src="<%= ENV['RAILS_RELATIVE_URL_ROOT'] %>/assets/plotkit/Layout.js"></script>
<script type="text/javascript" src="<%= ENV['RAILS_RELATIVE_URL_ROOT'] %>/assets/plotkit/Canvas.js"></script>
<script type="text/javascript" src="<%= ENV['RAILS_RELATIVE_URL_ROOT'] %>/assets/plotkit/SweetCanvas.js"></script>

<p id="notice"><%= notice %></p>

<h1>
  <%= @project.name %>
</h1>


<% if current_user.is_admin? then %>
<p>
  <b>Risk configuration:</b>
  <%= link_to @project.risk_configuration.name, @project.risk_configuration %>
</p>
<% end %>



<table class="risk_list">
	<tr>
		<th></th>
		<% @project.risk_configuration.risk_levels.sort_by(&:weight).each do |risk_level| %>
			<th class="impact"><%= risk_level.name %></th>
		<% end %>
	</tr>
<% @project.visible_impacts.each do |impact| %>
	<tr class="<%= impact.hidden ? "muted" : "" %>">
		<th><%= impact.name %></th>
		<% @project.risk_configuration.risk_levels.sort_by(&:weight).each do |risk_level| %>
			<% 
			 count =  @project.risks.select{|r| r.impact == impact && r.risk_level == risk_level}.count()
			 count_overridden = @project.risks.select{|r| r.impact == impact && r.risk_level == risk_level && r.accepted_override }.count() 
			 weightclass = "low"
			 if (risk_level.weight > impact.risk_level.weight) then
			 	weightclass = "medium"
			 end
			 if (impact.risk_level.above != NIL && risk_level.weight > impact.risk_level.above.weight ) then
			 	weightclass = "high"
			 end

			%>
			<td class="<%= weightclass %> <%= (count - count_overridden) > 0 && (risk_level.weight > impact.risk_level.weight ? "tooHigh" : "") %>">
				<a href="<%= project_risks_path(@project) %>?risklevel=<%= risk_level.id %>&impact=<%= impact.id %>">
					<%= count - count_overridden %>
					<% if (count_overridden > 0)  %>
						+ <span><%= count_overridden %></span>
					<% end %>
				</a>
			</td>
		<% end %>
	</tr>
<% end %>
</table>


<table class="risk_list risk_levels">
  <tr>
    <th rowspan="<%= @project.risk_configuration.risk_probabilities.count + 2 %>" class="vertical_label"><br><br><label>Probabilities</label></th>
    <th> </th>
    <th colspan="<%= @project.risk_configuration.risk_consequences.count %>"><label>Consequences</label></th>
  </tr>
  <tr>
    <th> </th>
    <% @project.risk_configuration.risk_consequences.sort_by{|p| p.weight}.each do |rc| %>
      <th><%= rc.name %></th>
    <% end %>
  </tr>
<% @project.risk_configuration.risk_probabilities.sort_by{|p| p.weight}.each do |rp| %>
  <tr>
    <th><%= rp.name %></th>
    <% @project.risk_configuration.risk_consequences.sort_by{|p| p.weight}.each do |rc| %>
      <% rl = @project.risk_configuration.find_level(rp, rc) %>
      <td class="risk_level_<%= rl.color %>"><%= 
        @project.risks.select{|r| r.risk_consequence == rc && r.risk_probability == rp}.count()
      %></td>
    <% end %>
  </tr>
<% end %>
</table>




<div class="graphContainer loading">
<canvas class="demo" id="graph"></canvas>
</div>





<script>

var oldGraphWidth = -1;
var oldScroll = -1;
var graphData;
var days = <%= @project.days_since_creation %>;


function toggleZoom() {
    var elm = $(".graphContainer");
    var width = oldGraphWidth;
    if (elm.hasClass("zoomed")) {
        oldScroll = elm.scrollLeft();
        elm.removeClass("zoomed");
    } else {
        elm.addClass("zoomed");
        width = days * 10;
    }
    elm.text("");
    $("<canvas>").attr("id", "graph").attr("width", width).appendTo(elm);
    drawGraph();
    elm.css({"width": "auto"});
    if (elm.hasClass("zoomed")) {
        elm.scrollLeft(oldScroll > -1 ? oldScroll : width);
    }
}



function drawGraph() {
    var zoomed = $(".graphContainer").hasClass("zoomed");
    var xTicks = graphData.week_ticks;
    if (days > 100 && !zoomed) {
        xTicks = graphData.month_ticks;
    }
    var layout = new PlotKit.Layout("line", {yTickPrecision: 0, xTicks: xTicks });
    layout.addDataset("Too high", graphData.total_risk );
    layout.addDataset("Accepted", graphData.accepted_risk);
    layout.evaluate();
    var canvas = MochiKit.DOM.getElement("graph");
    var plotter = new PlotKit.SweetCanvasRenderer(canvas, layout, {
        "colorScheme": [Color.fromRGB(0.87, 0.32, 0.30, 1), Color.fromRGB(0.37, 0.73, 0.37, 1)]
    });
    plotter.render();
}

function loadGraph() {
    if (oldGraphWidth == -1) {
        //oldGraphWidth = $("#graph").attr("width");
        oldGraphWidth = $(".graphContainer").width();
        $("#graph").attr("width", oldGraphWidth)
        $(".graphContainer").click(toggleZoom);
    }
    $.getJSON('<%= graph_project_path %>', function(data) {
        graphData = data;
        $(".graphContainer").removeClass("loading");
        drawGraph();
    });
}

MochiKit.DOM.addLoadEvent(loadGraph);
</script>