config/routes.rb
Riskmanager::Application.routes.draw do
  
    scope ENV['RAILS_RELATIVE_URL_ROOT'] do 
      resources :projects do
        get 'export',      :on => :member
        get 'tags',        :on => :member
        get 'graph',       :on => :member
        get 'risk_levels', :on => :member

        resources :risk_assets

        resources :risks do
          get 'checklists',      :on => :collection
          get 'assets',          :on => :member
          post 'assign_asset',   :on => :member
          post 'unassign_asset', :on => :member
          resources :comments
          resources :checklists do
            resources :checklist_items
          end
          resources :attachments
        end
      end

      resources :risk_configurations do
      	resources :impacts
      	resources :risk_consequences
      	resources :risk_probabilities
      	resources :risk_levels
        resources :risk_asset_values
      end

      resources :attachments

      resources :users

      resource :changes
      resource :not_approved
      resource :additional_infos
      resource :session

      get  "oauth/new"  => "oauth#new"
      get  "oauth/code" => "oauth#code"

      get  "login"                  => "login#index"
      get  "login/failed"           => "login#failed"
      get  "login/connect"          => "login#connect"
      post "login/connectaccounts"  => "login#connectaccounts"
      get  "login/switch"           => "login#switch"

      get '/auth/:provider/callback' => 'sessions#create'
      match '/auth/failure' => 'sessions#failure'

      root :to => "home#index"
    end

  match "*path" => "home#fix"
  root :to => redirect("/risk/")

end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_filter :ensure_signed_in
  before_filter :ensure_approved  

  def index
    if (params[:term]) then
      @assets = current_project.assets.where("name LIKE :term", {:term => params[:term] + "%"})
    else
      @assets = current_project.assets.sort_by{|a| a.asset_value.name }
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @assets }
    end
  end

  def show
    @asset = Asset.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @asset }
    end
  end


  def new
    @asset = Asset.new

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @asset }
    end
  end

  def edit
    @asset = Asset.find(params[:id])
  end

  def create
    @asset = Asset.new(params[:asset])
    @asset.project = current_project
    respond_to do |format|
      if @asset.save
        format.html { redirect_to(project_assets_path(current_project), :notice => 'Asset was successfully created.') }
        format.json  { render :json => @asset, :status => :created}
      else
        format.html { render :action => "new" }
        format.json  { render :json => @asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @asset = Asset.find(params[:id])

    respond_to do |format|
      if @asset.update_attributes(params[:asset])
        format.html { redirect_to(project_assets_path(current_project), :notice => 'Asset was successfully updated.') }
        format.json  { render :json => @asset }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @asset.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @asset = Asset.find(params[:id])
    @asset.destroy

    respond_to do |format|
      format.html { redirect_to(project_assets_path(current_project)) }
      format.json  { head :ok }
    end
  end






end

app/views/assets/_form.html.erb
<%= form_for([current_project, @asset]) do |f| %>
  <% if @asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :rows => 5 %>
  </div>  

  <div class="field">
    <%= f.label :asset_value %>
  <%= select("asset", "asset_value_id", current_project.risk_configuration.asset_values.sort_by{|l| l.weight }.reverse().collect{|l| [l.name + " - " + (l.description || ""), l.id] } ) %>
  </div>

  <div class="actions">
    <%= f.submit :class =>"btn btn-primary" %>
  </div>
<% end %>

app/views/assets/index.html.erb
<% content_for :title, " - Assets" %>


<% content_for :sidebar do %>
  <li class="nav-header">Value Definitions</li>
    <table class="table">
      <% current_project.risk_configuration.asset_values.sort_by{|v| v.weight}.reverse.each do |v| %>
        <tr>
          <th><%= v.name %></th>
          <td><%= v.description %></td>
        </tr>
      <% end %>
    </table>
<% end %>


<%= link_to current_project.name, project_path(current_project) %>  &gt; 
Assets

<h1>Assets</h1>

<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th>Description</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @assets.sort_by{|a| a.name }.each do |asset| %>
      <tr>
        <td data-sort-key="<%= asset.name %>"><%= link_to asset.name, [current_project, asset] %></td>
        <td data-sort-key="<%= asset.asset_value.weight %>" title="<%= asset.asset_value.description %>"><%= asset.asset_value.name %></td>
        <td><%= asset.description %></td>
        <td><%= button_to 'Edit', edit_project_asset_path(current_project, asset), :method => :get %></td>
        <td><%= button_to 'Delete', [current_project, asset], :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<a href="<%= new_project_asset_path(current_project) %>"  class="btn"><i class="icon-plus"></i> New asset</a>

app/views/assets/show.html.erb
<%= content_for :title, " - " << @asset.project.name << " \\ " << @asset.name %>

<p id="notice"><%= notice %></p>

<%= link_to @asset.project.name, project_path(current_project) %>  &gt; 
<%= link_to "Assets", project_assets_path(current_project) %> &gt;
<%= @asset.name %>

<h1><%= @asset.name %></h1>

<h5>Value</h5> 
<%= @asset.asset_value.name %> - <%= @asset.asset_value.description %>

<div id="description">
<h5>Description</h5> 
  <%= @asset.description %>
</div>



<h3>Risks associated with this asset:</h3>
<table class="risks table table-striped table-condensed">
  <thead>
    <tr>
      <th>Impact</th>
      <th>Id</th>
      <th>Title</th>
      <th>Consequence</th>
      <th>Probability</th>
      <th>Risk level</th>
    </tr>
  </thead>
  <tbody>
<% @asset.risks.sort_by{|r| [r.impact.name, r.title]}.each do |risk| %>
  <tr>
    <td><%= risk.impact.name %></td>
    <td data-sort-key="<%= risk.id %>"><%= risk.id %></td>
    <td><%= link_to risk.title, project_risk_path(current_project, risk) %></td>
    <td data-sort-key="<%= risk.risk_consequence.weight %>"><%= risk.risk_consequence.name %></td>
    <td data-sort-key="<%= risk.risk_probability.weight %>"><%= risk.risk_probability.name %></td>
    <td data-sort-key="<%= risk.risk_level.weight %>" class="<%= risk.accepted ? "" : "tooHigh" %>"><%= risk.risk_level.name %></td>
    
  </tr>
<% end %>
</tbody>
</table>